-- Migration: city_import_queue
-- Creates a queue table for bulk city POI imports and seeds it with ~300 top tourist cities.

CREATE TABLE IF NOT EXISTS city_import_queue (
  id           serial PRIMARY KEY,
  city         text NOT NULL,
  country_code char(2) NOT NULL,
  status       text NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending', 'processing', 'done', 'failed')),
  poi_count    int,
  error_msg    text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

CREATE INDEX city_import_queue_pending_idx
  ON city_import_queue (id)
  WHERE status = 'pending';

-- ============================================================
-- Seed: ~300 top global tourist destinations
-- ============================================================
INSERT INTO city_import_queue (city, country_code) VALUES

-- North America (USA)
('New York City', 'US'),
('Los Angeles', 'US'),
('Chicago', 'US'),
('San Francisco', 'US'),
('Las Vegas', 'US'),
('Miami', 'US'),
('New Orleans', 'US'),
('Washington D.C.', 'US'),
('Boston', 'US'),
('Seattle', 'US'),
('Honolulu', 'US'),
('Nashville', 'US'),
('Orlando', 'US'),
('San Diego', 'US'),
('Portland', 'US'),
('Austin', 'US'),
('Philadelphia', 'US'),
('Denver', 'US'),
('Atlanta', 'US'),
('Savannah', 'US'),

-- North America (Canada)
('Toronto', 'CA'),
('Vancouver', 'CA'),
('Montreal', 'CA'),
('Quebec City', 'CA'),
('Calgary', 'CA'),
('Ottawa', 'CA'),
('Banff', 'CA'),
('Victoria', 'CA'),

-- North America (Mexico)
('Mexico City', 'MX'),
('Cancun', 'MX'),
('Guadalajara', 'MX'),
('Oaxaca', 'MX'),
('San Miguel de Allende', 'MX'),
('Merida', 'MX'),
('Puerto Vallarta', 'MX'),
('Tulum', 'MX'),

-- Caribbean
('Havana', 'CU'),
('San Juan', 'PR'),
('Nassau', 'BS'),
('Bridgetown', 'BB'),
('Willemstad', 'CW'),
('Kingston', 'JM'),
('Fort-de-France', 'MQ'),
('Philipsburg', 'SX'),
('Oranjestad', 'AW'),
('Santo Domingo', 'DO'),

-- South America
('Buenos Aires', 'AR'),
('Rio de Janeiro', 'BR'),
('São Paulo', 'BR'),
('Lima', 'PE'),
('Bogotá', 'CO'),
('Cartagena', 'CO'),
('Santiago', 'CL'),
('Cusco', 'PE'),
('Quito', 'EC'),
('Montevideo', 'UY'),
('Medellín', 'CO'),
('Salvador', 'BR'),
('Florianopolis', 'BR'),
('Asuncion', 'PY'),
('La Paz', 'BO'),
('Sucre', 'BO'),
('Valparaíso', 'CL'),

-- Western Europe (United Kingdom & Ireland)
('London', 'GB'),
('Edinburgh', 'GB'),
('Manchester', 'GB'),
('Liverpool', 'GB'),
('Oxford', 'GB'),
('Cambridge', 'GB'),
('Bath', 'GB'),
('York', 'GB'),
('Dublin', 'IE'),
('Galway', 'IE'),

-- Western Europe (France)
('Paris', 'FR'),
('Nice', 'FR'),
('Lyon', 'FR'),
('Marseille', 'FR'),
('Bordeaux', 'FR'),
('Strasbourg', 'FR'),
('Avignon', 'FR'),
('Mont Saint-Michel', 'FR'),

-- Western Europe (Germany, Austria, Switzerland)
('Berlin', 'DE'),
('Munich', 'DE'),
('Hamburg', 'DE'),
('Cologne', 'DE'),
('Frankfurt', 'DE'),
('Heidelberg', 'DE'),
('Rothenburg ob der Tauber', 'DE'),
('Dresden', 'DE'),
('Vienna', 'AT'),
('Salzburg', 'AT'),
('Innsbruck', 'AT'),
('Zurich', 'CH'),
('Geneva', 'CH'),
('Lucerne', 'CH'),
('Bern', 'CH'),
('Interlaken', 'CH'),

-- Western Europe (Netherlands, Belgium, Luxembourg)
('Amsterdam', 'NL'),
('Rotterdam', 'NL'),
('The Hague', 'NL'),
('Bruges', 'BE'),
('Brussels', 'BE'),
('Ghent', 'BE'),
('Antwerp', 'BE'),
('Luxembourg City', 'LU'),

-- Western Europe (Nordic)
('Copenhagen', 'DK'),
('Stockholm', 'SE'),
('Oslo', 'NO'),
('Helsinki', 'FI'),
('Reykjavik', 'IS'),
('Bergen', 'NO'),
('Gothenburg', 'SE'),
('Aarhus', 'DK'),
('Tromsø', 'NO'),

-- Southern Europe (Spain & Portugal)
('Barcelona', 'ES'),
('Madrid', 'ES'),
('Seville', 'ES'),
('Granada', 'ES'),
('Toledo', 'ES'),
('Córdoba', 'ES'),
('San Sebastián', 'ES'),
('Valencia', 'ES'),
('Málaga', 'ES'),
('Bilbao', 'ES'),
('Palma', 'ES'),
('Lisbon', 'PT'),
('Porto', 'PT'),
('Sintra', 'PT'),
('Évora', 'PT'),
('Faro', 'PT'),

-- Southern Europe (Italy)
('Rome', 'IT'),
('Venice', 'IT'),
('Florence', 'IT'),
('Milan', 'IT'),
('Naples', 'IT'),
('Amalfi', 'IT'),
('Cinque Terre', 'IT'),
('Bologna', 'IT'),
('Turin', 'IT'),
('Siena', 'IT'),
('Palermo', 'IT'),
('Verona', 'IT'),
('Pisa', 'IT'),
('Bari', 'IT'),
('Lecce', 'IT'),

-- Southern Europe (Greece & Cyprus)
('Athens', 'GR'),
('Santorini', 'GR'),
('Mykonos', 'GR'),
('Thessaloniki', 'GR'),
('Rhodes', 'GR'),
('Heraklion', 'GR'),
('Corfu', 'GR'),
('Nicosia', 'CY'),

-- Central & Eastern Europe
('Prague', 'CZ'),
('Budapest', 'HU'),
('Warsaw', 'PL'),
('Kraków', 'PL'),
('Vienna', 'AT'),
('Bratislava', 'SK'),
('Ljubljana', 'SI'),
('Zagreb', 'HR'),
('Dubrovnik', 'HR'),
('Split', 'HR'),
('Sarajevo', 'BA'),
('Kotor', 'ME'),
('Tallinn', 'EE'),
('Riga', 'LV'),
('Vilnius', 'LT'),
('Bucharest', 'RO'),
('Cluj-Napoca', 'RO'),
('Sofia', 'BG'),
('Belgrade', 'RS'),
('Skopje', 'MK'),
('Tirana', 'AL'),
('Valletta', 'MT'),
('Minsk', 'BY'),
('Kyiv', 'UA'),
('Lviv', 'UA'),

-- Middle East
('Istanbul', 'TR'),
('Ankara', 'TR'),
('Cappadocia', 'TR'),
('Ephesus', 'TR'),
('Dubai', 'AE'),
('Abu Dhabi', 'AE'),
('Muscat', 'OM'),
('Doha', 'QA'),
('Manama', 'BH'),
('Kuwait City', 'KW'),
('Riyadh', 'SA'),
('Jeddah', 'SA'),
('Amman', 'JO'),
('Petra', 'JO'),
('Jerusalem', 'IL'),
('Tel Aviv', 'IL'),
('Beirut', 'LB'),
('Tehran', 'IR'),
('Isfahan', 'IR'),
('Shiraz', 'IR'),

-- Africa (North)
('Cairo', 'EG'),
('Luxor', 'EG'),
('Alexandria', 'EG'),
('Marrakech', 'MA'),
('Fes', 'MA'),
('Casablanca', 'MA'),
('Tangier', 'MA'),
('Tunis', 'TN'),
('Algiers', 'DZ'),
('Tripoli', 'LY'),

-- Africa (Sub-Saharan)
('Cape Town', 'ZA'),
('Johannesburg', 'ZA'),
('Durban', 'ZA'),
('Nairobi', 'KE'),
('Mombasa', 'KE'),
('Accra', 'GH'),
('Lagos', 'NG'),
('Abuja', 'NG'),
('Dakar', 'SN'),
('Addis Ababa', 'ET'),
('Dar es Salaam', 'TZ'),
('Zanzibar City', 'TZ'),
('Kampala', 'UG'),
('Kigali', 'RW'),
('Windhoek', 'NA'),
('Gaborone', 'BW'),
('Victoria', 'SC'),
('Antananarivo', 'MG'),
('Maputo', 'MZ'),

-- South Asia
('Mumbai', 'IN'),
('Delhi', 'IN'),
('Agra', 'IN'),
('Jaipur', 'IN'),
('Varanasi', 'IN'),
('Goa', 'IN'),
('Bangalore', 'IN'),
('Chennai', 'IN'),
('Kolkata', 'IN'),
('Udaipur', 'IN'),
('Amritsar', 'IN'),
('Hyderabad', 'IN'),
('Kochi', 'IN'),
('Rishikesh', 'IN'),
('Kathmandu', 'NP'),
('Pokhara', 'NP'),
('Colombo', 'LK'),
('Sigiriya', 'LK'),
('Dhaka', 'BD'),
('Karachi', 'PK'),
('Lahore', 'PK'),
('Islamabad', 'PK'),

-- East Asia
('Tokyo', 'JP'),
('Kyoto', 'JP'),
('Osaka', 'JP'),
('Hiroshima', 'JP'),
('Nara', 'JP'),
('Sapporo', 'JP'),
('Fukuoka', 'JP'),
('Nikko', 'JP'),
('Beijing', 'CN'),
('Shanghai', 'CN'),
('Guangzhou', 'CN'),
('Chengdu', 'CN'),
('Xi''an', 'CN'),
('Guilin', 'CN'),
('Hangzhou', 'CN'),
('Suzhou', 'CN'),
('Zhangjiajie', 'CN'),
('Hong Kong', 'HK'),
('Macau', 'MO'),
('Seoul', 'KR'),
('Busan', 'KR'),
('Gyeongju', 'KR'),
('Taipei', 'TW'),

-- Southeast Asia
('Bangkok', 'TH'),
('Chiang Mai', 'TH'),
('Phuket', 'TH'),
('Ayutthaya', 'TH'),
('Singapore', 'SG'),
('Kuala Lumpur', 'MY'),
('Penang', 'MY'),
('Langkawi', 'MY'),
('Bali', 'ID'),
('Jakarta', 'ID'),
('Yogyakarta', 'ID'),
('Lombok', 'ID'),
('Manila', 'PH'),
('Cebu', 'PH'),
('Ho Chi Minh City', 'VN'),
('Hanoi', 'VN'),
('Hoi An', 'VN'),
('Ha Long', 'VN'),
('Siem Reap', 'KH'),
('Phnom Penh', 'KH'),
('Luang Prabang', 'LA'),
('Vientiane', 'LA'),
('Yangon', 'MM'),
('Mandalay', 'MM'),
('Naypyidaw', 'MM'),
('Brunei', 'BN'),

-- Oceania
('Sydney', 'AU'),
('Melbourne', 'AU'),
('Brisbane', 'AU'),
('Perth', 'AU'),
('Adelaide', 'AU'),
('Cairns', 'AU'),
('Gold Coast', 'AU'),
('Hobart', 'AU'),
('Auckland', 'NZ'),
('Queenstown', 'NZ'),
('Wellington', 'NZ'),
('Christchurch', 'NZ'),
('Rotorua', 'NZ'),
('Suva', 'FJ'),
('Apia', 'WS'),
('Nuku''alofa', 'TO'),
('Port Vila', 'VU'),
('Papeete', 'PF'),

-- Central Asia & Caucasus
('Almaty', 'KZ'),
('Nur-Sultan', 'KZ'),
('Tashkent', 'UZ'),
('Samarkand', 'UZ'),
('Bukhara', 'UZ'),
('Tbilisi', 'GE'),
('Yerevan', 'AM'),
('Baku', 'AZ'),
('Bishkek', 'KG'),
('Dushanbe', 'TJ'),
('Ashgabat', 'TM'),

-- Russia & Central/North Asia
('Moscow', 'RU'),
('Saint Petersburg', 'RU'),
('Vladivostok', 'RU'),
('Irkutsk', 'RU'),
('Kazan', 'RU'),
('Ulaanbaatar', 'MN');
